language: scala
jdk: oraclejdk8
before_install:
  - git fetch --tags
dist: trusty
sudo: required
before_install:
- curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -x
script: sbt -batch ++${TRAVIS_SCALA_VERSION} test
stages:
  - name: test
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)
jobs:
  include:
    - scala: 2.12.7
    - stage: release
      script: sbt ci-release
cache:
  directories:
  - "$HOME/.cache"
  - "$HOME/.coursier"
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"
