language: scala
jdk: oraclejdk8
scala: 2.12.8
before_install:
  - curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -x
dist: trusty
sudo: required
git:
  depth: false
stages:
  - name: test
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)
  - name: upload-launcher
    if: tag IS present
  - name: update-sbt-extras
    if: tag IS present
script: sbt -batch ++${TRAVIS_SCALA_VERSION} +publishLocal "testOnly coursier.sbtlauncher.${TEST_NAME}"
jobs:
  include:
    - env: TEST_NAME=ScriptedTests
    - env: TEST_NAME=SbtPre12Tests
    - env: TEST_NAME=Sbt1203Tests
    - env: TEST_NAME=Sbt12Tests
    - stage: release
      script: sbt ci-release
    - stage: upload-launcher
      env: REPO="coursier/sbt-launcher" NAME="csbt" CMD="./scripts/generate-csbt.sh -f --bat=true"
      script: scripts/upload-launcher/upload-gh-release.sh
    - stage: update-sbt-extras
      script: scripts/update-sbt-extras.sh
cache:
  directories:
  - "$HOME/.cache"
  - "$HOME/.coursier"
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"
